Conference.create!([
  {name: "ACC"},
  {name: "AAC"},
  {name: "BIG-12"},
  {name: "BIG-10"},
  {name: "CONFERENCE-USA"},
  {name: "IA-INDEPENDENTS"},
  {name: "MID-AMERICAN"},
  {name: "MOUNTAIN-WEST"},
  {name: "PAC-12"},
  {name: "SEC"},
  {name: "SUN-BELT"},
  ])


Team.create!([
  {name: "Cardinals", nickname: "Louisville", conference_id: 1, league: "NCAAF", key: "LOU"},
  {name: "Demon Deacons", nickname: "Wake Forest", conference_id: 1, league: "NCAAF", key: "WF"},
  {name: "Eagles", nickname: "Boston College", conference_id: 1, league: "NCAAF", key: "BC"},
  {name: "Orange", nickname: "Syracuse", conference_id: 1, league: "NCAAF", key: "SYR"},
  {name: "Seminoles", nickname: "Florida State", conference_id: 1, league: "NCAAF", key: "FSU"},
  {name: "Tigers", nickname: "Clemson", conference_id: 1, league: "NCAAF", key: "CLE"},
  {name: "Wolfpack", nickname: "North Carolina State", conference_id: 1, league: "NCAAF", key: "NCST"},
  {name: "Blue Devils", nickname: "Duke", conference_id: 1, league: "NCAAF", key: "DUK"},
  {name: "Cavaliers", nickname: "Virginia", conference_id: 1, league: "NCAAF", key: "UVA"},
  {name: "Hokies", nickname: "Virginia Tech", conference_id: 1, league: "NCAAF", key: "VT"},
  {name: "Hurricanes", nickname: "Miami (FL)", conference_id: 1, league: "NCAAF", key: "MFL"},
  {name: "Panthers", nickname: "Pittsburgh", conference_id: 1, league: "NCAAF", key: "PIT"},
  {name: "Tar Heels", nickname: "North Carolina", conference_id: 1, league: "NCAAF", key: "NC"},
  {name: "Yellow Jackets", nickname: "Georgia Tech", conference_id: 1, league: "NCAAF", key: "GT"},
  {name: "Bearcats", nickname: "Cincinnati", conference_id: 2, league: "NCAAF", key: "CIN"},
  {name: "Bulls", nickname: "South Florida", conference_id: 2, league: "NCAAF", key: "USF"},
  {name: "Huskies", nickname: "Connecticut", conference_id: 2, league: "NCAAF", key: "UCONN"},
  {name: "Knights", nickname: "UCF", conference_id: 2, league: "NCAAF", key: "UCF"},
  {name: "Owls", nickname: "Temple", conference_id: 2, league: "NCAAF", key: "TEM"},
  {name: "Pirates", nickname: "East Carolina", conference_id: 2, league: "NCAAF", key: "ECU"},
  {name: "Cougars", nickname: "Houston", conference_id: 2, league: "NCAAF", key: "HOU"},
  {name: "Golden Hurricane", nickname: "Tulsa", conference_id: 2, league: "NCAAF", key: "TSA"},
  {name: "Green Wave", nickname: "Tulane", conference_id: 2, league: "NCAAF", key: "TUL"},
  {name: "Midshipmen", nickname: "Navy", conference_id: 2, league: "NCAAF", key: "NAV"},
  {name: "Mustangs", nickname: "Southern Methodist", conference_id: 2, league: "NCAAF", key: "SMU"},
  {name: "Tigers", nickname: "Memphis", conference_id: 2, league: "NCAAF", key: "MEM"},
  {name: "Bears", nickname: "Baylor", conference_id: 3, league: "NCAAF", key: "BAY"},
  {name: "Cowboys", nickname: "Oklahoma State", conference_id: 3, league: "NCAAF", key: "OKS"},
  {name: "Cyclones", nickname: "Iowa State", conference_id: 3, league: "NCAAF", key: "ISU"},
  {name: "Horned Frogs", nickname: "TCU", conference_id: 3, league: "NCAAF", key: "TCU"},
  {name: "Jayhawks", nickname: "Kansas", conference_id: 3, league: "NCAAF", key: "KAN"},
  {name: "Longhorns", nickname: "Texas", conference_id: 3, league: "NCAAF", key: "TEX"},
  {name: "Mountaineers", nickname: "West Virginia", conference_id: 3, league: "NCAAF", key: "WVU"},
  {name: "Red Raiders", nickname: "Texas Tech", conference_id: 3, league: "NCAAF", key: "TT"},
  {name: "Sooners", nickname: "Oklahoma", conference_id: 3, league: "NCAAF", key: "OKL"},
  {name: "Wildcats", nickname: "Kansas State", conference_id: 3, league: "NCAAF", key: "KST"},
  {name: "Buckeyes", nickname: "Ohio State", conference_id: 4, league: "NCAAF", key: "OSU"},
  {name: "Hoosiers", nickname: "Indiana", conference_id: 4, league: "NCAAF", key: "IU"},
  {name: "Nittany Lions", nickname: "Penn State", conference_id: 4, league: "NCAAF", key: "PSU"},
  {name: "Scarlet Knights", nickname: "Rutgers", conference_id: 4, league: "NCAAF", key: "RUT"},
  {name: "Spartans", nickname: "Michigan State", conference_id: 4, league: "NCAAF", key: "MSU"},
  {name: "Terrapins", nickname: "Maryland", conference_id: 4, league: "NCAAF", key: "MAR"},
  {name: "Wolverines", nickname: "Michigan", conference_id: 4, league: "NCAAF", key: "MICH"},
  {name: "Badgers", nickname: "Wisconsin", conference_id: 4, league: "NCAAF", key: "WIS"},
  {name: "Boilermakers", nickname: "Purdue", conference_id: 4, league: "NCAAF", key: "PUR"},
  {name: "Cornhuskers", nickname: "Nebraska", conference_id: 4, league: "NCAAF", key: "NEB"},
  {name: "Fighting Illini", nickname: "Illinois", conference_id: 4, league: "NCAAF", key: "ILL"},
  {name: "Golden Gophers", nickname: "Minnesota", conference_id: 4, league: "NCAAF", key: "MIN"},
  {name: "Hawkeyes", nickname: "Iowa", conference_id: 4, league: "NCAAF", key: "IOW"},
  {name: "Wildcats", nickname: "Northwestern", conference_id: 4, league: "NCAAF", key: "NW"},
  {name: "49ers", nickname: "Charlotte", conference_id: 5, league: "NCAAF", key: "CHA"},
  {name: "Blue Raiders", nickname: "Middle Tennessee", conference_id: 5, league: "NCAAF", key: "MTS"},
  {name: "Golden Panthers", nickname: "Florida International", conference_id: 5, league: "NCAAF", key: "FIU"},
  {name: "Hilltoppers", nickname: "Western Kentucky", conference_id: 5, league: "NCAAF", key: "WKY"},
  {name: "Monarchs", nickname: "Old Dominion", conference_id: 5, league: "NCAAF", key: "ODU"},
  {name: "Owls", nickname: "Florida Atlantic", conference_id: 5, league: "NCAAF", key: "FAU"},
  {name: "Thundering Herd", nickname: "Marshall", conference_id: 5, league: "NCAAF", key: "MSH"},
  {name: "Bulldogs", nickname: "Louisiana Tech", conference_id: 5, league: "NCAAF", key: "LT"},
  {name: "Golden Eagles", nickname: "Southern Miss", conference_id: 5, league: "NCAAF", key: "USM"},
  {name: "Mean Green", nickname: "North Texas", conference_id: 5, league: "NCAAF", key: "NTX"},
  {name: "Miners", nickname: "UTEP", conference_id: 5, league: "NCAAF", key: "TEP"},
  {name: "Owls", nickname: "Rice", conference_id: 5, league: "NCAAF", key: "RICE"},
  {name: "Roadrunners", nickname: "UTSA", conference_id: 5, league: "NCAAF", key: "UTSA"},
  {name: "Black Knights", nickname: "Army", conference_id: 6, league: "NCAAF", key: "ARM"},
  {name: "Cougars", nickname: "Brigham Young", conference_id: 6, league: "NCAAF", key: "BYU"},
  {name: "Fighting Irish", nickname: "Notre Dame", conference_id: 6, league: "NCAAF", key: "ND"},
  {name: "Minutemen", nickname: "Massachusetts", conference_id: 6, league: "NCAAF", key: "UMASS"},
  {name: "Bobcats", nickname: "Ohio", conference_id: 7, league: "NCAAF", key: "OHI"},
  {name: "Bulls", nickname: "Buffalo", conference_id: 7, league: "NCAAF", key: "BUF"},
  {name: "Falcons", nickname: "Bowling Green", conference_id: 7, league: "NCAAF", key: "BGN"},
  {name: "Golden Flashes", nickname: "Kent State", conference_id: 7, league: "NCAAF", key: "KNT"},
  {name: "RedHawks", nickname: "Miami (OH)", conference_id: 7, league: "NCAAF", key: "MOH"},
  {name: "Zips", nickname: "Akron", conference_id: 7, league: "NCAAF", key: "AKR"},
  {name: "Broncos", nickname: "Western Michigan", conference_id: 7, league: "NCAAF", key: "WMC"},
  {name: "Cardinals", nickname: "Ball State", conference_id: 7, league: "NCAAF", key: "BALL"},
  {name: "Chippewas", nickname: "Central Michigan", conference_id: 7, league: "NCAAF", key: "CMC"},
  {name: "Eagles", nickname: "Eastern Michigan", conference_id: 7, league: "NCAAF", key: "EMC"},
  {name: "Huskies", nickname: "Northern Illinois", conference_id: 7, league: "NCAAF", key: "NIL"},
  {name: "Rockets", nickname: "Toledo", conference_id: 7, league: "NCAAF", key: "TOL"},
  {name: "Aggies", nickname: "Utah State", conference_id: 8, league: "NCAAF", key: "UTS"},
  {name: "Broncos", nickname: "Boise State", conference_id: 8, league: "NCAAF", key: "BOISE"},
  {name: "Cowboys", nickname: "Wyoming", conference_id: 8, league: "NCAAF", key: "WYO"},
  {name: "Falcons", nickname: "Air Force", conference_id: 8, league: "NCAAF", key: "AF"},
  {name: "Lobos", nickname: "New Mexico", conference_id: 8, league: "NCAAF", key: "NM"},
  {name: "Rams", nickname: "Colorado State", conference_id: 8, league: "NCAAF", key: "CSU"},
  {name: "Aztecs", nickname: "San Diego State", conference_id: 8, league: "NCAAF", key: "SDSU"},
  {name: "Bulldogs", nickname: "Fresno State", conference_id: 8, league: "NCAAF", key: "FRE"},
  {name: "Rebels", nickname: "UNLV", conference_id: 8, league: "NCAAF", key: "UNLV"},
  {name: "Spartans", nickname: "San Jose State", conference_id: 8, league: "NCAAF", key: "SJS"},
  {name: "Warriors", nickname: "Hawaii", conference_id: 8, league: "NCAAF", key: "HAW"},
  {name: "Wolf Pack", nickname: "Nevada", conference_id: 8, league: "NCAAF", key: "NEV"},
  {name: "Bruins", nickname: "UCLA", conference_id: 9, league: "NCAAF", key: "UCLA"},
  {name: "Buffaloes", nickname: "Colorado", conference_id: 9, league: "NCAAF", key: "COL"},
  {name: "Sun Devils", nickname: "Arizona State", conference_id: 9, league: "NCAAF", key: "ASU"},
  {name: "Trojans", nickname: "USC", conference_id: 9, league: "NCAAF", key: "USC"},
  {name: "Utes", nickname: "Utah", conference_id: 9, league: "NCAAF", key: "UTH"},
  {name: "Wildcats", nickname: "Arizona", conference_id: 9, league: "NCAAF", key: "ARI"},
  {name: "Bears", nickname: "California", conference_id: 9, league: "NCAAF", key: "CAL"},
  {name: "Beavers", nickname: "Oregon State", conference_id: 9, league: "NCAAF", key: "ORS"},
  {name: "Cardinal", nickname: "Stanford", conference_id: 9, league: "NCAAF", key: "STA"},
  {name: "Cougars", nickname: "Washington State", conference_id: 9, league: "NCAAF", key: "WST"},
  {name: "Ducks", nickname: "Oregon", conference_id: 9, league: "NCAAF", key: "ORE"},
  {name: "Huskies", nickname: "Washington", conference_id: 9, league: "NCAAF", key: "WAS"},
  {name: "Aggies", nickname: "Texas A&M", conference_id: 10, league: "NCAAF", key: "TXAM"},
  {name: "Bulldogs", nickname: "Mississippi State", conference_id: 10, league: "NCAAF", key: "MSST"},
  {name: "Crimson Tide", nickname: "Alabama", conference_id: 10, league: "NCAAF", key: "BAMA"},
  {name: "Razorbacks", nickname: "Arkansas", conference_id: 10, league: "NCAAF", key: "ARK"},
  {name: "Rebels", nickname: "Ole Miss", conference_id: 10, league: "NCAAF", key: "MIS"},
  {name: "Tigers", nickname: "Auburn", conference_id: 10, league: "NCAAF", key: "AUB"},
  {name: "Tigers", nickname: "LSU", conference_id: 10, league: "NCAAF", key: "LSU"},
  {name: "Bulldogs", nickname: "Georgia", conference_id: 10, league: "NCAAF", key: "UGA"},
  {name: "Commodores", nickname: "Vanderbilt", conference_id: 10, league: "NCAAF", key: "VAN"},
  {name: "Gamecocks", nickname: "South Carolina", conference_id: 10, league: "NCAAF", key: "SC"},
  {name: "Gators", nickname: "Florida", conference_id: 10, league: "NCAAF", key: "FLA"},
  {name: "Tigers", nickname: "Missouri", conference_id: 10, league: "NCAAF", key: "MIZ"},
  {name: "Volunteers", nickname: "Tennessee", conference_id: 10, league: "NCAAF", key: "TEN"},
  {name: "Wildcats", nickname: "Kentucky", conference_id: 10, league: "NCAAF", key: "KEN"},
  {name: "Aggies", nickname: "New Mexico State", conference_id: 11, league: "NCAAF", key: "NMS"},
  {name: "Bobcats", nickname: "Texas State", conference_id: 11, league: "NCAAF", key: "TXST"},
  {name: "Eagles", nickname: "Georgia Southern", conference_id: 11, league: "NCAAF", key: "GSO"},
  {name: "Jaguars", nickname: "South Alabama", conference_id: 11, league: "NCAAF", key: "SAB"},
  {name: "Mountaineers", nickname: "Appalachian State", conference_id: 11, league: "NCAAF", key: "APP"},
  {name: "Panthers", nickname: "Georgia State", conference_id: 11, league: "NCAAF", key: "GST"},
  {name: "Ragin' Cajuns", nickname: "Louisiana-Lafayette", conference_id: 11, league: "NCAAF", key: "ULL"},
  {name: "Red Wolves", nickname: "Arkansas State", conference_id: 11, league: "NCAAF", key: "ARKS"},
  {name: "Trojans", nickname: "Troy", conference_id: 11, league: "NCAAF", key: "TRY"},
  {name: "Vandals", nickname: "Idaho", conference_id: 11, league: "NCAAF", key: "IDA"},
  {name: "Warhawks", nickname: "Louisiana-Monroe", conference_id: 11, league: "NCAAF", key: "ULM"}
])
