Team.create!([
  {name: "Cardinals", nickname: "Louisville", conference: "ACC", league: "NCAAF"},
  {name: "Demon Deacons", nickname: "Wake Forest", conference: "ACC", league: "NCAAF"},
  {name: "Eagles", nickname: "Boston College", conference: "ACC", league: "NCAAF"},
  {name: "Orange", nickname: "Syracuse", conference: "ACC", league: "NCAAF"},
  {name: "Seminoles", nickname: "Florida State", conference: "ACC", league: "NCAAF"},
  {name: "Tigers", nickname: "Clemson", conference: "ACC", league: "NCAAF"},
  {name: "Wolfpack", nickname: "North Carolina State", conference: "ACC", league: "NCAAF"},
  {name: "Blue Devils", nickname: "Duke", conference: "ACC", league: "NCAAF"},
  {name: "Cavaliers", nickname: "Virginia", conference: "ACC", league: "NCAAF"},
  {name: "Hokies", nickname: "Virginia Tech", conference: "ACC", league: "NCAAF"},
  {name: "Hurricanes", nickname: "Miami (FL)", conference: "ACC", league: "NCAAF"},
  {name: "Panthers", nickname: "Pittsburgh", conference: "ACC", league: "NCAAF"},
  {name: "Tar Heels", nickname: "North Carolina", conference: "ACC", league: "NCAAF"},
  {name: "Yellow Jackets", nickname: "Georgia Tech", conference: "ACC", league: "NCAAF"},
  {name: "Bearcats", nickname: "Cincinnati", conference: "AAC", league: "NCAAF"},
  {name: "Bulls", nickname: "South Florida", conference: "AAC", league: "NCAAF"},
  {name: "Huskies", nickname: "Connecticut", conference: "AAC", league: "NCAAF"},
  {name: "Knights", nickname: "UCF", conference: "AAC", league: "NCAAF"},
  {name: "Owls", nickname: "Temple", conference: "AAC", league: "NCAAF"},
  {name: "Pirates", nickname: "East Carolina", conference: "AAC", league: "NCAAF"},
  {name: "Cougars", nickname: "Houston", conference: "AAC", league: "NCAAF"},
  {name: "Golden Hurricane", nickname: "Tulsa", conference: "AAC", league: "NCAAF"},
  {name: "Green Wave", nickname: "Tulane", conference: "AAC", league: "NCAAF"},
  {name: "Midshipmen", nickname: "Navy", conference: "AAC", league: "NCAAF"},
  {name: "Mustangs", nickname: "Southern Methodist", conference: "AAC", league: "NCAAF"},
  {name: "Tigers", nickname: "Memphis", conference: "AAC", league: "NCAAF"},
  {name: "Bears", nickname: "Baylor", conference: "BIG-12", league: "NCAAF"},
  {name: "Cowboys", nickname: "Oklahoma State", conference: "BIG-12", league: "NCAAF"},
  {name: "Cyclones", nickname: "Iowa State", conference: "BIG-12", league: "NCAAF"},
  {name: "Horned Frogs", nickname: "TCU", conference: "BIG-12", league: "NCAAF"},
  {name: "Jayhawks", nickname: "Kansas", conference: "BIG-12", league: "NCAAF"},
  {name: "Longhorns", nickname: "Texas", conference: "BIG-12", league: "NCAAF"},
  {name: "Mountaineers", nickname: "West Virginia", conference: "BIG-12", league: "NCAAF"},
  {name: "Red Raiders", nickname: "Texas Tech", conference: "BIG-12", league: "NCAAF"},
  {name: "Sooners", nickname: "Oklahoma", conference: "BIG-12", league: "NCAAF"},
  {name: "Wildcats", nickname: "Kansas State", conference: "BIG-12", league: "NCAAF"},
  {name: "Buckeyes", nickname: "Ohio State", conference: "BIG-TEN", league: "NCAAF"},
  {name: "Hoosiers", nickname: "Indiana", conference: "BIG-TEN", league: "NCAAF"},
  {name: "Nittany Lions", nickname: "Penn State", conference: "BIG-TEN", league: "NCAAF"},
  {name: "Scarlet Knights", nickname: "Rutgers", conference: "BIG-TEN", league: "NCAAF"},
  {name: "Spartans", nickname: "Michigan State", conference: "BIG-TEN", league: "NCAAF"},
  {name: "Terrapins", nickname: "Maryland", conference: "BIG-TEN", league: "NCAAF"},
  {name: "Wolverines", nickname: "Michigan", conference: "BIG-TEN", league: "NCAAF"},
  {name: "Badgers", nickname: "Wisconsin", conference: "BIG-TEN", league: "NCAAF"},
  {name: "Boilermakers", nickname: "Purdue", conference: "BIG-TEN", league: "NCAAF"},
  {name: "Cornhuskers", nickname: "Nebraska", conference: "BIG-TEN", league: "NCAAF"},
  {name: "Fighting Illini", nickname: "Illinois", conference: "BIG-TEN", league: "NCAAF"},
  {name: "Golden Gophers", nickname: "Minnesota", conference: "BIG-TEN", league: "NCAAF"},
  {name: "Hawkeyes", nickname: "Iowa", conference: "BIG-TEN", league: "NCAAF"},
  {name: "Wildcats", nickname: "Northwestern", conference: "BIG-TEN", league: "NCAAF"},
  {name: "49ers", nickname: "Charlotte", conference: "CONFERENCE-USA", league: "NCAAF"},
  {name: "Blue Raiders", nickname: "Middle Tennessee", conference: "CONFERENCE-USA", league: "NCAAF"},
  {name: "Golden Panthers", nickname: "Florida International", conference: "CONFERENCE-USA", league: "NCAAF"},
  {name: "Hilltoppers", nickname: "Western Kentucky", conference: "CONFERENCE-USA", league: "NCAAF"},
  {name: "Monarchs", nickname: "Old Dominion", conference: "CONFERENCE-USA", league: "NCAAF"},
  {name: "Owls", nickname: "Florida Atlantic", conference: "CONFERENCE-USA", league: "NCAAF"},
  {name: "Thundering Herd", nickname: "Marshall", conference: "CONFERENCE-USA", league: "NCAAF"},
  {name: "Bulldogs", nickname: "Louisiana Tech", conference: "CONFERENCE-USA", league: "NCAAF"},
  {name: "Golden Eagles", nickname: "Southern Miss", conference: "CONFERENCE-USA", league: "NCAAF"},
  {name: "Mean Green", nickname: "North Texas", conference: "CONFERENCE-USA", league: "NCAAF"},
  {name: "Miners", nickname: "UTEP", conference: "CONFERENCE-USA", league: "NCAAF"},
  {name: "Owls", nickname: "Rice", conference: "CONFERENCE-USA", league: "NCAAF"},
  {name: "Roadrunners", nickname: "UTSA", conference: "CONFERENCE-USA", league: "NCAAF"},
  {name: "Black Knights", nickname: "Army", conference: "IA-INDEPENDENTS", league: "NCAAF"},
  {name: "Cougars", nickname: "Brigham Young", conference: "IA-INDEPENDENTS", league: "NCAAF"},
  {name: "Fighting Irish", nickname: "Notre Dame", conference: "IA-INDEPENDENTS", league: "NCAAF"},
  {name: "Minutemen", nickname: "Massachusetts", conference: "IA-INDEPENDENTS", league: "NCAAF"},
  {name: "Bobcats", nickname: "Ohio", conference: "MID-AMERICAN", league: "NCAAF"},
  {name: "Bulls", nickname: "Buffalo", conference: "MID-AMERICAN", league: "NCAAF"},
  {name: "Falcons", nickname: "Bowling Green", conference: "MID-AMERICAN", league: "NCAAF"},
  {name: "Golden Flashes", nickname: "Kent State", conference: "MID-AMERICAN", league: "NCAAF"},
  {name: "RedHawks", nickname: "Miami (OH)", conference: "MID-AMERICAN", league: "NCAAF"},
  {name: "Zips", nickname: "Akron", conference: "MID-AMERICAN", league: "NCAAF"},
  {name: "Broncos", nickname: "Western Michigan", conference: "MID-AMERICAN", league: "NCAAF"},
  {name: "Cardinals", nickname: "Ball State", conference: "MID-AMERICAN", league: "NCAAF"},
  {name: "Chippewas", nickname: "Central Michigan", conference: "MID-AMERICAN", league: "NCAAF"},
  {name: "Eagles", nickname: "Eastern Michigan", conference: "MID-AMERICAN", league: "NCAAF"},
  {name: "Huskies", nickname: "Northern Illinois", conference: "MID-AMERICAN", league: "NCAAF"},
  {name: "Rockets", nickname: "Toledo", conference: "MID-AMERICAN", league: "NCAAF"},
  {name: "Aggies", nickname: "Utah State", conference: "MOUNTAIN-WEST", league: "NCAAF"},
  {name: "Broncos", nickname: "Boise State", conference: "MOUNTAIN-WEST", league: "NCAAF"},
  {name: "Cowboys", nickname: "Wyoming", conference: "MOUNTAIN-WEST", league: "NCAAF"},
  {name: "Falcons", nickname: "Air Force", conference: "MOUNTAIN-WEST", league: "NCAAF"},
  {name: "Lobos", nickname: "New Mexico", conference: "MOUNTAIN-WEST", league: "NCAAF"},
  {name: "Rams", nickname: "Colorado State", conference: "MOUNTAIN-WEST", league: "NCAAF"},
  {name: "Aztecs", nickname: "San Diego State", conference: "MOUNTAIN-WEST", league: "NCAAF"},
  {name: "Bulldogs", nickname: "Fresno State", conference: "MOUNTAIN-WEST", league: "NCAAF"},
  {name: "Rebels", nickname: "UNLV", conference: "MOUNTAIN-WEST", league: "NCAAF"},
  {name: "Spartans", nickname: "San Jose State", conference: "MOUNTAIN-WEST", league: "NCAAF"},
  {name: "Warriors", nickname: "Hawaii", conference: "MOUNTAIN-WEST", league: "NCAAF"},
  {name: "Wolf Pack", nickname: "Nevada", conference: "MOUNTAIN-WEST", league: "NCAAF"},
  {name: "Bruins", nickname: "UCLA", conference: "PAC-12", league: "NCAAF"},
  {name: "Buffaloes", nickname: "Colorado", conference: "PAC-12", league: "NCAAF"},
  {name: "Sun Devils", nickname: "Arizona State", conference: "PAC-12", league: "NCAAF"},
  {name: "Trojans", nickname: "USC", conference: "PAC-12", league: "NCAAF"},
  {name: "Utes", nickname: "Utah", conference: "PAC-12", league: "NCAAF"},
  {name: "Wildcats", nickname: "Arizona", conference: "PAC-12", league: "NCAAF"},
  {name: "Bears", nickname: "California", conference: "PAC-12", league: "NCAAF"},
  {name: "Beavers", nickname: "Oregon State", conference: "PAC-12", league: "NCAAF"},
  {name: "Cardinal", nickname: "Stanford", conference: "PAC-12", league: "NCAAF"},
  {name: "Cougars", nickname: "Washington State", conference: "PAC-12", league: "NCAAF"},
  {name: "Ducks", nickname: "Oregon", conference: "PAC-12", league: "NCAAF"},
  {name: "Huskies", nickname: "Washington", conference: "PAC-12", league: "NCAAF"},
  {name: "Aggies", nickname: "Texas A&M", conference: "SEC", league: "NCAAF"},
  {name: "Bulldogs", nickname: "Mississippi State", conference: "SEC", league: "NCAAF"},
  {name: "Crimson Tide", nickname: "Alabama", conference: "SEC", league: "NCAAF"},
  {name: "Razorbacks", nickname: "Arkansas", conference: "SEC", league: "NCAAF"},
  {name: "Rebels", nickname: "Ole Miss", conference: "SEC", league: "NCAAF"},
  {name: "Tigers", nickname: "Auburn", conference: "SEC", league: "NCAAF"},
  {name: "Tigers", nickname: "LSU", conference: "SEC", league: "NCAAF"},
  {name: "Bulldogs", nickname: "Georgia", conference: "SEC", league: "NCAAF"},
  {name: "Commodores", nickname: "Vanderbilt", conference: "SEC", league: "NCAAF"},
  {name: "Gamecocks", nickname: "South Carolina", conference: "SEC", league: "NCAAF"},
  {name: "Gators", nickname: "Florida", conference: "SEC", league: "NCAAF"},
  {name: "Tigers", nickname: "Missouri", conference: "SEC", league: "NCAAF"},
  {name: "Volunteers", nickname: "Tennessee", conference: "SEC", league: "NCAAF"},
  {name: "Wildcats", nickname: "Kentucky", conference: "SEC", league: "NCAAF"},
  {name: "Aggies", nickname: "New Mexico State", conference: "SUN-BELT", league: "NCAAF"},
  {name: "Bobcats", nickname: "Texas State", conference: "SUN-BELT", league: "NCAAF"},
  {name: "Eagles", nickname: "Georgia Southern", conference: "SUN-BELT", league: "NCAAF"},
  {name: "Jaguars", nickname: "South Alabama", conference: "SUN-BELT", league: "NCAAF"},
  {name: "Mountaineers", nickname: "Appalachian State", conference: "SUN-BELT", league: "NCAAF"},
  {name: "Panthers", nickname: "Georgia State", conference: "SUN-BELT", league: "NCAAF"},
  {name: "Ragin' Cajuns", nickname: "Louisiana-Lafayette", conference: "SUN-BELT", league: "NCAAF"},
  {name: "Red Wolves", nickname: "Arkansas State", conference: "SUN-BELT", league: "NCAAF"},
  {name: "Trojans", nickname: "Troy", conference: "SUN-BELT", league: "NCAAF"},
  {name: "Vandals", nickname: "Idaho", conference: "SUN-BELT", league: "NCAAF"},
  {name: "Warhawks", nickname: "Louisiana-Monroe", conference: "SUN-BELT", league: "NCAAF"}
])
