Conference.create!([
  {name: "ACC"},
  {name: "AAC"},
  {name: "BIG-12"},
  {name: "BIG-10"},
  {name: "CONFERENCE-USA"},
  {name: "IA-INDEPENDENTS"},
  {name: "MID-AMERICAN"},
  {name: "MOUNTAIN-WEST"},
  {name: "PAC-12"},
  {name: "SEC"},
  {name: "SUN-BELT"},
  ])


Team.create!([
  {nickname: "Cardinals", name: "Louisville", conference_id: 1, league: "NCAAF", key: "LOU"},
  {nickname: "Demon Deacons", name: "Wake Forest", conference_id: 1, league: "NCAAF", key: "WF"},
  {nickname: "Eagles", name: "Boston College", conference_id: 1, league: "NCAAF", key: "BC"},
  {nickname: "Orange", name: "Syracuse", conference_id: 1, league: "NCAAF", key: "SYR"},
  {nickname: "Seminoles", name: "Florida State", conference_id: 1, league: "NCAAF", key: "FSU"},
  {nickname: "Tigers", name: "Clemson", conference_id: 1, league: "NCAAF", key: "CLE"},
  {nickname: "Wolfpack", name: "North Carolina State", conference_id: 1, league: "NCAAF", key: "NCST"},
  {nickname: "Blue Devils", name: "Duke", conference_id: 1, league: "NCAAF", key: "DUK"},
  {nickname: "Cavaliers", name: "Virginia", conference_id: 1, league: "NCAAF", key: "UVA"},
  {nickname: "Hokies", name: "Virginia Tech", conference_id: 1, league: "NCAAF", key: "VT"},
  {nickname: "Hurricanes", name: "Miami (FL)", conference_id: 1, league: "NCAAF", key: "MFL"},
  {nickname: "Panthers", name: "Pittsburgh", conference_id: 1, league: "NCAAF", key: "PIT"},
  {nickname: "Tar Heels", name: "North Carolina", conference_id: 1, league: "NCAAF", key: "NC"},
  {nickname: "Yellow Jackets", name: "Georgia Tech", conference_id: 1, league: "NCAAF", key: "GT"},
  {nickname: "Bearcats", name: "Cincinnati", conference_id: 2, league: "NCAAF", key: "CIN"},
  {nickname: "Bulls", name: "South Florida", conference_id: 2, league: "NCAAF", key: "USF"},
  {nickname: "Huskies", name: "Connecticut", conference_id: 2, league: "NCAAF", key: "UCONN"},
  {nickname: "Knights", name: "UCF", conference_id: 2, league: "NCAAF", key: "UCF"},
  {nickname: "Owls", name: "Temple", conference_id: 2, league: "NCAAF", key: "TEM"},
  {nickname: "Pirates", name: "East Carolina", conference_id: 2, league: "NCAAF", key: "ECU"},
  {nickname: "Cougars", name: "Houston", conference_id: 2, league: "NCAAF", key: "HOU"},
  {nickname: "Golden Hurricane", name: "Tulsa", conference_id: 2, league: "NCAAF", key: "TSA"},
  {nickname: "Green Wave", name: "Tulane", conference_id: 2, league: "NCAAF", key: "TUL"},
  {nickname: "Midshipmen", name: "Navy", conference_id: 2, league: "NCAAF", key: "NAV"},
  {nickname: "Mustangs", name: "Southern Methodist", conference_id: 2, league: "NCAAF", key: "SMU"},
  {nickname: "Tigers", name: "Memphis", conference_id: 2, league: "NCAAF", key: "MEM"},
  {nickname: "Bears", name: "Baylor", conference_id: 3, league: "NCAAF", key: "BAY"},
  {nickname: "Cowboys", name: "Oklahoma State", conference_id: 3, league: "NCAAF", key: "OKS"},
  {nickname: "Cyclones", name: "Iowa State", conference_id: 3, league: "NCAAF", key: "ISU"},
  {nickname: "Horned Frogs", name: "TCU", conference_id: 3, league: "NCAAF", key: "TCU"},
  {nickname: "Jayhawks", name: "Kansas", conference_id: 3, league: "NCAAF", key: "KAN"},
  {nickname: "Longhorns", name: "Texas", conference_id: 3, league: "NCAAF", key: "TEX"},
  {nickname: "Mountaineers", name: "West Virginia", conference_id: 3, league: "NCAAF", key: "WVU"},
  {nickname: "Red Raiders", name: "Texas Tech", conference_id: 3, league: "NCAAF", key: "TT"},
  {nickname: "Sooners", name: "Oklahoma", conference_id: 3, league: "NCAAF", key: "OKL"},
  {nickname: "Wildcats", name: "Kansas State", conference_id: 3, league: "NCAAF", key: "KST"},
  {nickname: "Buckeyes", name: "Ohio State", conference_id: 4, league: "NCAAF", key: "OSU"},
  {nickname: "Hoosiers", name: "Indiana", conference_id: 4, league: "NCAAF", key: "IU"},
  {nickname: "Nittany Lions", name: "Penn State", conference_id: 4, league: "NCAAF", key: "PSU"},
  {nickname: "Scarlet Knights", name: "Rutgers", conference_id: 4, league: "NCAAF", key: "RUT"},
  {nickname: "Spartans", name: "Michigan State", conference_id: 4, league: "NCAAF", key: "MSU"},
  {nickname: "Terrapins", name: "Maryland", conference_id: 4, league: "NCAAF", key: "MAR"},
  {nickname: "Wolverines", name: "Michigan", conference_id: 4, league: "NCAAF", key: "MICH"},
  {nickname: "Badgers", name: "Wisconsin", conference_id: 4, league: "NCAAF", key: "WIS"},
  {nickname: "Boilermakers", name: "Purdue", conference_id: 4, league: "NCAAF", key: "PUR"},
  {nickname: "Cornhuskers", name: "Nebraska", conference_id: 4, league: "NCAAF", key: "NEB"},
  {nickname: "Fighting Illini", name: "Illinois", conference_id: 4, league: "NCAAF", key: "ILL"},
  {nickname: "Golden Gophers", name: "Minnesota", conference_id: 4, league: "NCAAF", key: "MIN"},
  {nickname: "Hawkeyes", name: "Iowa", conference_id: 4, league: "NCAAF", key: "IOW"},
  {nickname: "Wildcats", name: "Northwestern", conference_id: 4, league: "NCAAF", key: "NW"},
  {nickname: "49ers", name: "Charlotte", conference_id: 5, league: "NCAAF", key: "CHA"},
  {nickname: "Blue Raiders", name: "Middle Tennessee", conference_id: 5, league: "NCAAF", key: "MTS"},
  {nickname: "Golden Panthers", name: "Florida International", conference_id: 5, league: "NCAAF", key: "FIU"},
  {nickname: "Hilltoppers", name: "Western Kentucky", conference_id: 5, league: "NCAAF", key: "WKY"},
  {nickname: "Monarchs", name: "Old Dominion", conference_id: 5, league: "NCAAF", key: "ODU"},
  {nickname: "Owls", name: "Florida Atlantic", conference_id: 5, league: "NCAAF", key: "FAU"},
  {nickname: "Thundering Herd", name: "Marshall", conference_id: 5, league: "NCAAF", key: "MSH"},
  {nickname: "Bulldogs", name: "Louisiana Tech", conference_id: 5, league: "NCAAF", key: "LT"},
  {nickname: "Golden Eagles", name: "Southern Miss", conference_id: 5, league: "NCAAF", key: "USM"},
  {nickname: "Mean Green", name: "North Texas", conference_id: 5, league: "NCAAF", key: "NTX"},
  {nickname: "Miners", name: "UTEP", conference_id: 5, league: "NCAAF", key: "TEP"},
  {nickname: "Owls", name: "Rice", conference_id: 5, league: "NCAAF", key: "RICE"},
  {nickname: "Roadrunners", name: "UTSA", conference_id: 5, league: "NCAAF", key: "UTSA"},
  {nickname: "Black Knights", name: "Army", conference_id: 6, league: "NCAAF", key: "ARM"},
  {nickname: "Cougars", name: "Brigham Young", conference_id: 6, league: "NCAAF", key: "BYU"},
  {nickname: "Fighting Irish", name: "Notre Dame", conference_id: 6, league: "NCAAF", key: "ND"},
  {nickname: "Minutemen", name: "Massachusetts", conference_id: 6, league: "NCAAF", key: "UMASS"},
  {nickname: "Bobcats", name: "Ohio", conference_id: 7, league: "NCAAF", key: "OHI"},
  {nickname: "Bulls", name: "Buffalo", conference_id: 7, league: "NCAAF", key: "BUF"},
  {nickname: "Falcons", name: "Bowling Green", conference_id: 7, league: "NCAAF", key: "BGN"},
  {nickname: "Golden Flashes", name: "Kent State", conference_id: 7, league: "NCAAF", key: "KNT"},
  {nickname: "RedHawks", name: "Miami (OH)", conference_id: 7, league: "NCAAF", key: "MOH"},
  {nickname: "Zips", name: "Akron", conference_id: 7, league: "NCAAF", key: "AKR"},
  {nickname: "Broncos", name: "Western Michigan", conference_id: 7, league: "NCAAF", key: "WMC"},
  {nickname: "Cardinals", name: "Ball State", conference_id: 7, league: "NCAAF", key: "BALL"},
  {nickname: "Chippewas", name: "Central Michigan", conference_id: 7, league: "NCAAF", key: "CMC"},
  {nickname: "Eagles", name: "Eastern Michigan", conference_id: 7, league: "NCAAF", key: "EMC"},
  {nickname: "Huskies", name: "Northern Illinois", conference_id: 7, league: "NCAAF", key: "NIL"},
  {nickname: "Rockets", name: "Toledo", conference_id: 7, league: "NCAAF", key: "TOL"},
  {nickname: "Aggies", name: "Utah State", conference_id: 8, league: "NCAAF", key: "UTS"},
  {nickname: "Broncos", name: "Boise State", conference_id: 8, league: "NCAAF", key: "BOISE"},
  {nickname: "Cowboys", name: "Wyoming", conference_id: 8, league: "NCAAF", key: "WYO"},
  {nickname: "Falcons", name: "Air Force", conference_id: 8, league: "NCAAF", key: "AF"},
  {nickname: "Lobos", name: "New Mexico", conference_id: 8, league: "NCAAF", key: "NM"},
  {nickname: "Rams", name: "Colorado State", conference_id: 8, league: "NCAAF", key: "CSU"},
  {nickname: "Aztecs", name: "San Diego State", conference_id: 8, league: "NCAAF", key: "SDSU"},
  {nickname: "Bulldogs", name: "Fresno State", conference_id: 8, league: "NCAAF", key: "FRE"},
  {nickname: "Rebels", name: "UNLV", conference_id: 8, league: "NCAAF", key: "UNLV"},
  {nickname: "Spartans", name: "San Jose State", conference_id: 8, league: "NCAAF", key: "SJS"},
  {nickname: "Warriors", name: "Hawaii", conference_id: 8, league: "NCAAF", key: "HAW"},
  {nickname: "Wolf Pack", name: "Nevada", conference_id: 8, league: "NCAAF", key: "NEV"},
  {nickname: "Bruins", name: "UCLA", conference_id: 9, league: "NCAAF", key: "UCLA"},
  {nickname: "Buffaloes", name: "Colorado", conference_id: 9, league: "NCAAF", key: "COL"},
  {nickname: "Sun Devils", name: "Arizona State", conference_id: 9, league: "NCAAF", key: "ASU"},
  {nickname: "Trojans", name: "USC", conference_id: 9, league: "NCAAF", key: "USC"},
  {nickname: "Utes", name: "Utah", conference_id: 9, league: "NCAAF", key: "UTH"},
  {nickname: "Wildcats", name: "Arizona", conference_id: 9, league: "NCAAF", key: "ARI"},
  {nickname: "Bears", name: "California", conference_id: 9, league: "NCAAF", key: "CAL"},
  {nickname: "Beavers", name: "Oregon State", conference_id: 9, league: "NCAAF", key: "ORS"},
  {nickname: "Cardinal", name: "Stanford", conference_id: 9, league: "NCAAF", key: "STA"},
  {nickname: "Cougars", name: "Washington State", conference_id: 9, league: "NCAAF", key: "WST"},
  {nickname: "Ducks", name: "Oregon", conference_id: 9, league: "NCAAF", key: "ORE"},
  {nickname: "Huskies", name: "Washington", conference_id: 9, league: "NCAAF", key: "WAS"},
  {nickname: "Aggies", name: "Texas A&M", conference_id: 10, league: "NCAAF", key: "TXAM"},
  {nickname: "Bulldogs", name: "Mississippi State", conference_id: 10, league: "NCAAF", key: "MSST"},
  {nickname: "Crimson Tide", name: "Alabama", conference_id: 10, league: "NCAAF", key: "BAMA"},
  {nickname: "Razorbacks", name: "Arkansas", conference_id: 10, league: "NCAAF", key: "ARK"},
  {nickname: "Rebels", name: "Ole Miss", conference_id: 10, league: "NCAAF", key: "MIS"},
  {nickname: "Tigers", name: "Auburn", conference_id: 10, league: "NCAAF", key: "AUB"},
  {nickname: "Tigers", name: "LSU", conference_id: 10, league: "NCAAF", key: "LSU"},
  {nickname: "Bulldogs", name: "Georgia", conference_id: 10, league: "NCAAF", key: "UGA"},
  {nickname: "Commodores", name: "Vanderbilt", conference_id: 10, league: "NCAAF", key: "VAN"},
  {nickname: "Gamecocks", name: "South Carolina", conference_id: 10, league: "NCAAF", key: "SC"},
  {nickname: "Gators", name: "Florida", conference_id: 10, league: "NCAAF", key: "FLA"},
  {nickname: "Tigers", name: "Missouri", conference_id: 10, league: "NCAAF", key: "MIZ"},
  {nickname: "Volunteers", name: "Tennessee", conference_id: 10, league: "NCAAF", key: "TEN"},
  {nickname: "Wildcats", name: "Kentucky", conference_id: 10, league: "NCAAF", key: "KEN"},
  {nickname: "Aggies", name: "New Mexico State", conference_id: 11, league: "NCAAF", key: "NMS"},
  {nickname: "Bobcats", name: "Texas State", conference_id: 11, league: "NCAAF", key: "TXST"},
  {nickname: "Eagles", name: "Georgia Southern", conference_id: 11, league: "NCAAF", key: "GSO"},
  {nickname: "Jaguars", name: "South Alabama", conference_id: 11, league: "NCAAF", key: "SAB"},
  {nickname: "Mountaineers", name: "Appalachian State", conference_id: 11, league: "NCAAF", key: "APP"},
  {nickname: "Panthers", name: "Georgia State", conference_id: 11, league: "NCAAF", key: "GST"},
  {nickname: "Ragin' Cajuns", name: "Louisiana-Lafayette", conference_id: 11, league: "NCAAF", key: "ULL"},
  {nickname: "Red Wolves", name: "Arkansas State", conference_id: 11, league: "NCAAF", key: "ARKS"},
  {nickname: "Trojans", name: "Troy", conference_id: 11, league: "NCAAF", key: "TRY"},
  {nickname: "Vandals", name: "Idaho", conference_id: 11, league: "NCAAF", key: "IDA"},
  {nickname: "Warhawks", name: "Louisiana-Monroe", conference_id: 11, league: "NCAAF", key: "ULM"}
])
